export const eventConstants = {
    ADD_NEW_EVENT_SUCCESS: 'ADD_NEW_EVENT_SUCCESS',
    ADD_OP_SUCCESS:'ADD_OP_SUCCESS',
    ADD_OP_FAILED:'ADD_OP_FAILED',
    DELETE_OP_SUCCESS:'DELETE_OP_SUCCESS',
    DELETE_OP_FAILED:'DELETE_OP_FAILED',
    GET_EVENT:'GET_EVENT',
    GET_EVENT_PARTICIPANTS: "GET_EVENT_PARTICIPANTS",
    ATTENDING_STATUS:'ATTENDING_STATUS',
    ATTENDANCE_OP_SUCCESS: "SHOW_QR_CODE",
    DISABLE_QR_CODE: "DISABLE_QR_CODE",
    CLEAR_ATTENDANCE_CALLBACK: "CLEAR_CALLBACKS"

};
